apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: devopsxebia/nodejs
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
